CREATE DATABASE DE18191

USE DE18191

CREATE TABLE BAITAP(
    MABT VARCHAR(5) PRIMARY KEY,
    MADK INT,
    TENBT CHAR(20)
)

CREATE TABLE DOKHO(
    MADK INT,
    DIEMDK INT,
    CONSTRAINT PK_MADK1 PRIMARY KEY (MADK),
)

CREATE TABLE NOPBAI(
    MABN VARCHAR(10) PRIMARY KEY,
    MATV VARCHAR(5),
    MABT VARCHAR(5),
    NGAYNOP SMALLDATETIME,
    DIEMHT INT,
    CONSTRAINT FK_MABT FOREIGN KEY (MABT) REFERENCES BAITAP(MABT),
)

CREATE TABLE THANHVIEN(
    MATV VARCHAR(5) PRIMARY KEY,
    TENTV CHAR(30),
    THUHANG INT,
    LOAITV CHAR(15),
    NGDK SMALLDATETIME,

)

-- INSERT DATA
SET DATEFORMAT DMY
INSERT INTO BAITAP(MABT,MADK,TENBT) VALUES('BT1',2,'BINARY TREE')
INSERT INTO BAITAP(MABT,MADK,TENBT) VALUES('BT2',1,'LINKED LIST')
INSERT INTO BAITAP(MABT,MADK,TENBT) VALUES('BT3',3,'HASH TABLE')

INSERT INTO DOKHO(MADK,DIEMDK) VALUES(1,20)
INSERT INTO DOKHO(MADK,DIEMDK) VALUES(2,40)
INSERT INTO DOKHO(MADK,DIEMDK) VALUES(3,60)

INSERT INTO NOPBAI(MABN,MATV,MABT,NGAYNOP,DIEMHT) VALUES('BN1','TV2','BT2','20/10/2018',30)
INSERT INTO NOPBAI(MABN,MATV,MABT,NGAYNOP,DIEMHT) VALUES('BN2','TV1','BT3','20/10/2018',0)
INSERT INTO NOPBAI(MABN,MATV,MABT,NGAYNOP,DIEMHT) VALUES('BN3','TV3','BT1','21/10/2018',20)

INSERT INTO THANHVIEN(MATV,TENTV,THUHANG,LOAITV,NGDK) VALUES('TV1','NGO THE PHUONG',70,'MEMBER','28/12/2017')
INSERT INTO THANHVIEN(MATV,TENTV,THUHANG,LOAITV,NGDK) VALUES('TV2','HO MAN DAT',35,'MODERATOR','11/11/2017')
INSERT INTO THANHVIEN(MATV,TENTV,THUHANG,LOAITV,NGDK) VALUES('TV3','NGUYEN TIEN LAM',60,'MEMBER','25/10/2017')

--TRIGGER 
GO
ALTER TRIGGER TRG_01 ON THANHVIEN
FOR INSERT,UPDATE
AS
BEGIN
    DECLARE @LOAITV CHAR(15),@THUHANG INT
    SELECT @LOAITV=LOAITV,@THUHANG=THUHANG
    FROM INSERTED
    IF (@LOAITV='MODERATOR')
        IF (@THUHANG>=40)
            BEGIN
                PRINT 'LOI: MODERATOR THU HANG PHAI HON 40'
                ROLLBACK TRANSACTION
            END
        ELSE
            PRINT ' THEM TV THANH CONG'
END

--TRIGGER 2
GO
CREATE TRIGGER TRG_02 ON DOKHO
FOR UPDATE
AS 
BEGIN
    DECLARE @MADK INT,@DIEMDK INT
    SELECT @MADK=MADK,@DIEMDK=DIEMDK
    FROM INSERTED
    IF EXISTS(
        SELECT DIEMHT
        FROM NOPBAI,BAITAP
        WHERE BAITAP.MADK=@MADK AND BAITAP.MABT=NOPBAI.MABT
            AND (@DIEMDK<DIEMHT)
    )
    BEGIN
        PRINT 'LOI: DIEM HT KO THE LON HON DIEM BT'
        ROLLBACK TRANSACTION
    END
    ELSE
        PRINT 'THANH CONG'
END

UPDATE DOKHO
SET DIEMDK=40
WHERE MADK=1
-- SAME ON NOPBAI
--SQL
