CREATE DATABASE DE3THI
USE DE3THI
-- TAO BANG
CREATE TABLE DOCGIA(
    MADG CHAR(5) PRIMARY KEY,
    HOTEN VARCHAR(30),
    NGAYSINH SMALLDATETIME,
    DIACHI VARCHAR(30),
    SODT VARCHAR(15),
)
CREATE TABLE SACH(
    MASACH CHAR(5) PRIMARY KEY,
    TENSACH VARCHAR(25),
    THELOAI VARCHAR(25),
    NHAXUATBAN VARCHAR(30)
)
CREATE TABLE PHIEUTHUE(
    MAPT CHAR(5) PRIMARY KEY,
    MADG CHAR(5),
    NGAYTHUE SMALLDATETIME,
    NGAYTRA SMALLDATETIME,
    SOSACHTHUE INT,
    CONSTRAINT FK_MADG FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG)
)
CREATE TABLE CHITIET_PT(
    MAPT CHAR(5),
    MASACH CHAR(5),
    CONSTRAINT PK_MAPT_MASACH PRIMARY KEY (MAPT,MASACH),
)