CREATE DATABASE DE3THI
USE DE3THI
-- TAO BANG
CREATE TABLE DOCGIA(
    MADG CHAR(5) PRIMARY KEY,
    HOTEN VARCHAR(30),
    NGAYSINH SMALLDATETIME,
    DIACHI VARCHAR(30),
    SODT VARCHAR(15),
)
CREATE TABLE SACH(
    MASACH CHAR(5) PRIMARY KEY,
    TENSACH VARCHAR(25),
    THELOAI VARCHAR(25),
    NHAXUATBAN VARCHAR(30)
)
CREATE TABLE PHIEUTHUE(
    MAPT CHAR(5) PRIMARY KEY,
    MADG CHAR(5),
    NGAYTHUE SMALLDATETIME,
    NGAYTRA SMALLDATETIME,
    SOSACHTHUE INT,
    CONSTRAINT FK_MADG FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG)
)

CREATE TABLE CHITIET_PT(
    MAPT CHAR(5),
    MASACH CHAR(5),
    CONSTRAINT PK_MAPT_MASACH PRIMARY KEY (MAPT,MASACH),
    CONSTRAINT FK_MAPT FOREIGN KEY (MAPT) REFERENCES PHIEUTHUE(MAPT),
    CONSTRAINT FK_MASACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
)
SET DATEFORMAT DMY
--TRIGGER
--2.1 
DROP TRIGGER PHIEUTHUE_NGAYTHUE
CREATE TRIGGER PHIEUTHUE_NGAYTHUE ON PHIEUTHUE
FOR UPDATE,INSERT
AS
BEGIN
    DECLARE @NGAYTHUE SMALLDATETIME,@NGAYTRA SMALLDATETIME
    SELECT @NGAYTHUE=NGAYTHUE,@NGAYTRA=NGAYTRA
    FROM INSERTED
        IF (DATEDIFF(DAY,@NGAYTHUE,@NGAYTRA)>=10)
            BEGIN
                PRINT 'LOI: THUE QUA 10 NGAY'
                ROLLBACK TRANSACTION
            END
        ELSE
            PRINT 'THEM PHIEU THUE THANH CONG'
END

--DATA TEST
INSERT INTO DOCGIA(MADG,HOTEN,NGAYSINH,DIACHI,SODT) VALUES ('DG01','NGUYEN VAN A','01/01/2001','123 PHI','0902123456')
INSERT INTO PHIEUTHUE(MAPT,MADG,NGAYTHUE,NGAYTRA,SOSACHTHUE) VALUES ('PT01','DG01','1/1/2020','10/1/2020',10)
UPDATE PHIEUTHUE
SET SOSACHTHUE=0
WHERE MAPT='PT01'
--2.2
CREATE TRIGGER SOSACHTHUE ON PHIEUTHUE
FOR INSERT,UPDATE
AS
BEGIN
    DECLARE @MAPT CHAR(5),@SOSACHTHUE INT,@SOLANTHUESACH INT
    SELECT @MAPT=MAPT,@SOSACHTHUE=SOSACHTHUE
    FROM inserted
    SELECT @SOLANTHUESACH=COUNT(CT.MAPT)
    FROM CHITIET_PT CT
    WHERE CT.MAPT=@MAPT
    IF (@SOLANTHUESACH=@SOSACHTHUE)
        PRINT  'NHAP SO SACH THUE THANH CONG'
    ELSE
        BEGIN 
            PRINT 'NHAP SO LUONG SACH SAI!'
            ROLLBACK TRANSACTION
        END
END
DROP TRIGGER SOSACHTHUE1
CREATE TRIGGER SOSACHTHUE1 ON CHITIET_PT
FOR INSERT,UPDATE
AS
BEGIN
    DECLARE @MAPT CHAR(5),@SOSACHTHUE INT,@SOLANTHUESACH INT
    SELECT @MAPT=MAPT
    FROM inserted
    SELECT @SOLANTHUESACH=COUNT(MAPT)
    FROM CHITIET_PT
    WHERE CHITIET_PT.MAPT=@MAPT
    SELECT @SOSACHTHUE=SOSACHTHUE
    FROM PHIEUTHUE
    WHERE PHIEUTHUE.MAPT=@MAPT
    IF (@SOLANTHUESACH=@SOSACHTHUE)
        PRINT  'NHAP SO SACH THUE THANH CONG'
    ELSE
        BEGIN 
            PRINT 'NHAP SO LUONG SACH SAI!'
            ROLLBACK TRANSACTION
        END
END
--DATA TEST....
INSERT INTO SACH(MASACH,TENSACH,THELOAI,NHAXUATBAN) VALUES ('S01','TIN HOC','TIN HOC','VN')
INSERT INTO CHITIET_PT(MAPT,MASACH) VALUES ('PT01','S01')
--SQL
--CAU1
SELECT DG.MADG,HOTEN
FROM DOCGIA DG,PHIEUTHUE PT,CHITIET_PT CT1,SACH
WHERE DG.MADG=PT.MADG AND PT.MAPT=CT1.MAPT AND CT1.MASACH=SACH.MASACH AND
    THELOAI='TIN HOC'

--CAU2
SELECT TOP 1 WITH TIES DG.MADG,HOTEN,COUNT (DISTINCT THELOAI) AS TONG
FROM DOCGIA DG,PHIEUTHUE PT,CHITIET_PT CT1,SACH
WHERE DG.MADG=PT.MADG AND PT.MAPT=CT1.MAPT AND CT1.MASACH=SACH.MASACH
GROUP BY DG.MADG,HOTEN
ORDER BY TONG DESC

--CAU3
SELECT THELOAI,S1.TENSACH,COUNT(CT1.MASACH) AS SOLUONGTHUE
FROM SACH S1,CHITIET_PT CT1
WHERE S1.MASACH=CT1.MASACH
GROUP BY THELOAI,S1.TENSACH
HAVING COUNT(CT1.MASACH) >= ALL(
    SELECT COUNT(CT1.MASACH)
    FROM SACH S2,CHITIET_PT CT1
    WHERE S2.MASACH=CT1.MASACH
    GROUP BY THELOAI
    HAVING S2.THELOAI=S1.THELOAI
)

    
