CREATE DATABASE DE4THI
USE DE4THI
CREATE TABLE KHACHHANG(
    MAKH CHAR(5) PRIMARY KEY,
    HOTEN VARCHAR(30),
    DIACHI VARCHAR(30),
    SODT VARCHAR(10),
    LOAIKH VARCHAR(10),
)
CREATE TABLE BANG_DIA(
    MABD CHAR(5) PRIMARY KEY,
    TENBD VARCHAR(25),
    THELOAI VARCHAR(25),
)
CREATE TABLE PHIEUTHUE(
    MAPT CHAR(5) PRIMARY KEY,
    MAKH CHAR(5),
    NGAYTHUE SMALLDATETIME,
    NGAYTRA SMALLDATETIME,
    SOLUONGTHUE INT,
    CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
)
CREATE TABLE CHITIET_PM(
    MAPT CHAR(5),
    MABD CHAR(5),
    CONSTRAINT PK_MAPT_MABD PRIMARY KEY (MAPT,MABD),
    CONSTRAINT FK_MAPT FOREIGN KEY (MAPT) REFERENCES PHIEUTHUE(MAPT),
    CONSTRAINT FK_MABD FOREIGN KEY (MABD) REFERENCES BANG_DIA(MABD),
)
