CREATE DATABASE DE4THI
USE DE4THI
CREATE TABLE KHACHHANG(
    MAKH CHAR(5) PRIMARY KEY,
    HOTEN VARCHAR(30),
    DIACHI VARCHAR(30),
    SODT VARCHAR(10),
    LOAIKH VARCHAR(10),
)
CREATE TABLE BANG_DIA(
    MABD CHAR(5) PRIMARY KEY,
    TENBD VARCHAR(25),
    THELOAI VARCHAR(25),
)
CREATE TABLE PHIEUTHUE(
    MAPT CHAR(5) PRIMARY KEY,
    MAKH CHAR(5),
    NGAYTHUE SMALLDATETIME,
    NGAYTRA SMALLDATETIME,
    SOLUONGTHUE INT,
    CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
)
CREATE TABLE CHITIET_PM(
    MAPT CHAR(5),
    MABD CHAR(5),
    CONSTRAINT PK_MAPT_MABD PRIMARY KEY (MAPT,MABD),
    CONSTRAINT FK_MAPT FOREIGN KEY (MAPT) REFERENCES PHIEUTHUE(MAPT),
    CONSTRAINT FK_MABD FOREIGN KEY (MABD) REFERENCES BANG_DIA(MABD),
)

--TRIGGER 
--2.1
CREATE TRIGGER THELOAI_BD ON BANG_DIA
FOR INSERT,UPDATE
AS
BEGIN
    DECLARE @THELOAI VARCHAR(25)
    SELECT @THELOAI=THELOAI
    FROM INSERTED
    IF (@THELOAI='CA NHAC' OR @THELOAI='PHIM HANH DONG' OR @THELOAI='PHIM TINH CAM'
        OR @THELOAI='PHIM HOAT HINH')
        PRINT 'NHAP BANG DIA THANH CONG'
    ELSE
        BEGIN
            PRINT 'NHAP SAI THE LOAI BANG DIA'
            ROLLBACK TRANSACTION
        END
END
--DATA TEST
INSERT INTO BANG_DIA(MABD,TENBD,THELOAI) VALUES ('BD01','BANG DIA 1','PHIM HANH DONG')

--2.2
CREATE TRIGGER SOLUONGTHUE ON PHIEUTHUE
FOR INSERT,UPDATE
AS
BEGIN
    DECLARE @MAKH CHAR(5),@SOLUONGTHUE INT,@LOAIKH VARCHAR(10)
    SELECT @MAKH=MAKH,@SOLUONGTHUE=SOLUONGTHUE
    FROM inserted
    SELECT @LOAIKH=LOAIKH
    FROM KHACHHANG
    WHERE KHACHHANG.MAKH=@MAKH
    IF (@SOLUONGTHUE>=5)
        IF (@LOAIKH='VIP')
            PRINT 'THEM PHIEU THUE THANH CONG!'
        ELSE
            BEGIN
                PRINT 'LOI: KHONG PHAI KHACH HANG VIP'
                ROLLBACK TRANSACTION
            END
    ELSE
        PRINT 'THEM PHIEU THUE THANH CONG'
END

CREATE TRIGGER LOAIKH ON KHACHHANG
FOR UPDATE
AS
BEGIN
    DECLARE @MAKH CHAR(5),@SOLUONGTHUE INT,@LOAIKH VARCHAR(10)
    SELECT @MAKH=MAKH,@LOAIKH=LOAIKH
    FROM inserted
    SELECT @SOLUONGTHUE=SOLUONGTHUE
    FROM PHIEUTHUE
    WHERE PHIEUTHUE.MAKH=@MAKH
    IF (@SOLUONGTHUE>=5)
        IF (@LOAIKH='VIP')
            PRINT 'SUA LOAI KHACH HANG THANH CONG!'
        ELSE
            BEGIN
                PRINT 'LOI: DANG THUE TREN 5 BANG DIA,KHONG THE THAY DOI LOAIKH'
                ROLLBACK TRANSACTION
            END
    ELSE
        PRINT 'SUA LOAI THANH CONG'
END

--TEST DATA
SET DATEFORMAT DMY
INSERT INTO PHIEUTHUE(MAPT,MAKH,NGAYTHUE,NGAYTRA,SOLUONGTHUE) VALUES ('PT01','KH01','1/1/2020','10/1/2020',10)
INSERT INTO KHACHHANG(MAKH,HOTEN,DIACHI,SODT,LOAIKH) VALUES ('KH01','NVA','222 PHI','0902123456','VIP')
UPDATE KHACHHANG
SET LOAIKH='VIP'
WHERE MAKH='KH01'

UPDATE BANG_DIA
SET THELOAI='PHIM TINH CAM'
WHERE MABD='BD01'
UPDATE PHIEUTHUE

SET SOLUONGTHUE=10
WHERE MAPT='PT01'
INSERT INTO CHITIET_PM(MAPT,MABD) VALUES ('PT01','BD01')

--SQL
--CAU1
SELECT KH.MAKH,HOTEN
FROM KHACHHANG KH,BANG_DIA BD,PHIEUTHUE PT,CHITIET_PM CT
WHERE KH.MAKH=PT.MAKH AND PT.MAPT=CT.MAPT AND CT.MABD=BD.MABD 
    AND THELOAI='PHIM TINH CAM' AND SOLUONGTHUE>=3

--CAU2
SELECT TOP 1 WITH TIES KH.MAKH,HOTEN,SUM(SOLUONGTHUE) AS TONG
FROM KHACHHANG KH,BANG_DIA BD,PHIEUTHUE PT,CHITIET_PM CT
WHERE KH.MAKH=PT.MAKH AND PT.MAPT=CT.MAPT AND CT.MABD=BD.MABD
    AND LOAIKH='VIP'
GROUP BY KH.MAKH,HOTEN
ORDER BY TONG DESC

--CAU3
SELECT THELOAI,KH1.HOTEN,SUM (SOLUONGTHUE) AS TONG
FROM KHACHHANG KH1,BANG_DIA BD,PHIEUTHUE PT,CHITIET_PM CT
WHERE KH1.MAKH=PT.MAKH AND PT.MAPT=CT.MAPT AND CT.MABD=BD.MABD
GROUP BY THELOAI,KH1.HOTEN
HAVING COUNT(SOLUONGTHUE) >= ALL(
    SELECT COUNT(SOLUONGTHUE)
    FROM KHACHHANG KH2,BANG_DIA BD,PHIEUTHUE PT,CHITIET_PM CT
    WHERE KH2.MAKH=PT.MAKH AND PT.MAPT=CT.MAPT AND CT.MABD=BD.MABD
    GROUP BY THELOAI,KH2.HOTEN
    HAVING  KH1.HOTEN=KH2.HOTEN
)