--CAU 10 PHAN 1
USE QLBH
ALTER TABLE KHACHHANG ADD 
CONSTRAINT CHECK_NGAY 
CHECK(YEAR(NGSINH) < YEAR(NGDK))
-- DATA MANUPALTING ....
-- CAU 2
USE QLBH
SELECT * INTO SANPHAM1 FROM SANPHAM
SELECT * INTO KHACHHANG1 FROM KHACHHANG
-- CAU 3
USE QLBH
UPDATE SANPHAM1
SET GIA=GIA*1.05
WHERE NUOCSX='THAILAN'
--CAU 4
USE QLBH
UPDATE SANPHAM1
SET GIA=GIA*0.95
WHERE NUOCSX='TRUNGQUOC' AND GIA<10000
-- CAU 5
USE QLBH
UPDATE KHACHHANG1
SET LOAIKH='VIP'
WHERE ((NGDK<'1/1/2017' AND DOANHSO>10000000) OR (NGDK>'1/1/2017' AND DOANHSO>2000000))
USE QLBH
SELECT LOAIKH
FROM KHACHHANG1
-- DE 2019-2020
--CAU 1
ALTER TABLE KHOAHOC ADD
CONSTRAIN CHECK_NGAYBATDAU
CHECK (NGBDKH<= NGKTKH)
--CAU 2
ALTER TABLE HOCPHAN ADD 
GHICHU VARCHAR(100)
--CAU 3
DELETE FROM CTDK 
WHERE SONGAYHT <3
--CAU 4
UPDATE HOCPHAN 
SET BATBUOC=1
WHERE MAKH='AV100' AND TUAN=15
--Phan 3
--Cau 1
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX='TRUNGQUOC'
--CAU 2
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
WHERE DVT='CAY' OR DVT='QUYEN'
--CAU 3
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
WHERE MASP LIKE 'B%01'
--CAU 4
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
WHERE GIA>=30000 AND GIA<=40000 AND NUOCSX='TRUNGQUOC'  
--CAU 5
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
WHERE (NUOCSX='TRUNGQUOC' OR NUOCSX='THAILAN') AND (GIA>=30000 AND GIA<=40000)
--CAU 6
USE QLBH
SELECT SOHD,TRIGIA
FROM HOADON
WHERE NGHD BETWEEN '1/1/2007' AND '1/2/2007'
--CAU 7
USE QLBH
SELECT SOHD,TRIGIA
FROM HOADON
WHERE MONTH(NGHD)=1 AND YEAR(NGHD)=2007
ORDER BY NGHD ASC,TRIGIA DESC
--CAU 8
USE QLBH
SELECT KH.MAKH,HOTEN
FROM KHACHHANG KH INNER JOIN HOADON HD ON KH.MAKH=HD.MAKH 
WHERE (HD.NGHD='01/01/2007')
--CAU 9
USE QLBH
SELECT HD.SOHD,TRIGIA
FROM NHANVIEN NV INNER JOIN HOADON HD ON NV.MANV=HD.MANV
WHERE (NGHD='10/28/2006') AND (NV.HOTEN='NGUYEN VAN B') 
--CAU 10
USE QLBH
SELECT SP.MASP,TENSP
FROM (HOADON HD INNER JOIN KHACHHANG KH ON HD.MAKH=KH.MAKH) INNER JOIN (CTHD cthd INNER JOIN SANPHAM SP ON cthd.MASP=SP.MASP) ON cthd.SOHD=HD.SOHD
WHERE KH.HOTEN='NGUYEN VAN A' AND (MONTH(HD.NGHD)=10 AND YEAR(HD.NGHD)=2006)    
--CAU 11
USE QLBH
SELECT DISTINCT SOHD
FROM CTHD
WHERE MASP='BB01' OR MASP='BB02'


-- PHAN III
--CAU 12
USE QLBH
SELECT DISTINCT SOHD
FROM CTHD
WHERE (MASP='BB02' OR MASP='BB01') AND (SL>=10 AND SL<=20)

--CAU 13
USE QLBH
SELECT SOHD
FROM CTHD 
WHERE (MASP='BB01' AND (SL>=10 AND SL<=20)) AND SOHD IN(
    SELECT SOHD
    FROM CTHD
    WHERE (MASP='BB02' AND (SL>=10 AND SL<=20))
)

--CAU 14
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX='TRUNGQUOC' OR MASP IN(
    SELECT MASP
    FROM CTHD
    WHERE SANPHAM.MASP=CTHD.MASP AND SOHD IN(
        SELECT SOHD 
        FROM HOADON
        WHERE HOADON.SOHD=CTHD.SOHD AND NGHD='01/01/2007'
    )
)
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX='TRUNGQUOC'
UNION
SELECT SP.MASP,TENSP
FROM SANPHAM SP,HOADON HD,CTHD
WHERE SP.MASP=CTHD.MASP AND CTHD.SOHD=HD.SOHD AND HD.NGHD='01/01/2007'
--CAU 15
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
WHERE MASP NOT IN(
    SELECT MASP
    FROM CTHD
    WHERE CTHD.MASP=SANPHAM.MASP
)
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
EXCEPT
SELECT SANPHAM.MASP,TENSP
FROM SANPHAM,CTHD
WHERE SANPHAM.MASP=CTHD.MASP
--CAU 16
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
WHERE MASP NOT IN(
    SELECT MASP
    FROM CTHD
    WHERE SOHD IN(
        SELECT SOHD
        FROM HOADON
        WHERE YEAR(NGHD)='2006'
    )
)
--CAU 17
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX='TRUNGQUOC' AND MASP NOT IN(
    SELECT MASP
    FROM CTHD
    WHERE SOHD IN(
        SELECT SOHD
        FROM HOADON
        WHERE YEAR(NGHD)=2006
    )
)
----------------
USE QLBH
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX='TRUNGQUOC' 
EXCEPT
SELECT SANPHAM.MASP,TENSP
FROM SANPHAM,CTHD,HOADON
WHERE SANPHAM.MASP=CTHD.MASP AND CTHD.SOHD=HOADON.SOHD AND YEAR(HOADON.NGHD)=2006

--CAU 20
USE QLBH
SELECT COUNT(SOHD) AS SL_SOHD 
FROM CTHD
WHERE SOHD IN(
    SELECT SOHD
    FROM HOADON
    WHERE MAKH IS NULL
)


--CAU 21
USE QLBH
SELECT COUNT (DISTINCT MASP) AS SOLUONG
FROM CTHD , HOADON HD 
WHERE CTHD.SOHD=HD.SOHD AND YEAR(HD.NGHD)=2006
--CAU 22
USE QLBH
SELECT MAX(TRIGIA) AS LONNHAT, MIN(TRIGIA) AS NHONHAT
FROM HOADON
--CAU 23
USE QLBH
SELECT AVG(TRIGIA) AS TRUNGBINH_HOADON
FROM HOADON
WHERE YEAR(NGHD)=2006
--CAU 24
USE QLBH
SELECT SUM(TRIGIA) AS DOANHTHU
FROM HOADON
WHERE YEAR(NGHD)=2006

--CAU 32
USE QLBH
SELECT COUNT(MASP) AS SOSP
FROM SANPHAM
WHERE NUOCSX='TRUNGQUOC'

--CAU 33
USE QLBH
SELECT NUOCSX,COUNT(MASP) AS SOSP
FROM SANPHAM
GROUP BY NUOCSX
--CAU 34
USE QLBH
SELECT NUOCSX,MIN(GIA) AS NHONHAT,MAX(GIA) AS LONNHAT,AVG(GIA) AS TRUNGBINH
FROM SANPHAM
GROUP BY NUOCSX
--CAU 35
USE QLBH
SELECT NGHD,SUM(TRIGIA) AS DOANHTHU_NGAY
FROM HOADON
GROUP BY NGHD
--CAU 36
USE QLBH
SELECT SP.TENSP,SUM(CTHD.SL) AS TONGSP
FROM SANPHAM SP,CTHD,HOADON HD
WHERE SP.MASP=CTHD.MASP AND HD.SOHD=CTHD.SOHD AND MONTH(HD.NGHD)=10 AND YEAR(HD.NGHD)=2006
GROUP BY SP.TENSP

--CAU 36 QUERY LONG
USE QLBH
SELECT MASP,SUM(SL) AS TONGSP
FROM CTHD 
WHERE SOHD IN(
    SELECT SOHD
    FROM HOADON
    WHERE MONTH(NGHD)=10 AND YEAR(NGHD)=2006
)
GROUP BY MASP

--CAU 37
USE QLBH
SELECT MONTH(NGHD),SUM(TRIGIA) AS DOANHTHU
FROM HOADON
WHERE YEAR(NGHD)=2006
GROUP BY MONTH(NGHD)

-- CREATE TRIGGER
--CAU 11
USE QLBH
DROP TRIGGER HOADON_TRIGGER
USE QLBH
CREATE TRIGGER HOADON_TRIGGER ON HOADON
FOR UPDATE,INSERT
AS
BEGIN
    DECLARE @NGAYHD smalldatetime, @MAKH CHAR(4), @NGAYDK SMALLDATETIME
    SELECT @NGAYHD=NGHD, @MAKH=@MAKH
    FROM INSERTED
    SELECT @NGAYDK=NGDK
    FROM KHACHHANG
    WHERE MAKH=@MAKH
    IF (@NGAYHD<@NGAYDK)
    BEGIN
        PRINT 'LOI: NGAY HOA DON KHONG HOP LE!'
        ROLLBACK TRANSACTION
    END
    ELSE
    BEGIN
        PRINT 'THEM MOT HOA DON THANH CONG!'
    END
END
USE QLBH
DROP TRIGGER KHACHHANG_TRIGGER
CREATE TRIGGER KHACHHANG_TRIGGER ON KHACHHANG
FOR UPDATE
AS
BEGIN
    DECLARE @NGAYHD SMALLDATETIME, @MAKH CHAR(4), @NGAYDK SMALLDATETIME
    SELECT @NGAYDK=NGDK,@MAKH=MAKH
    FROM inserted
    SELECT @NGAYHD=NGHD
    FROM HOADON
    WHERE MAKH=@MAKH
    IF (@NGAYHD<@NGAYDK)
    BEGIN
        PRINT 'LOI: NGAY DANG KY KHONG HOP LE!'
        ROLLBACK TRANSACTION
    END
    ELSE
    BEGIN
        PRINT 'THEM KHACH HANG DON THANH CONG!'
    END
END
SET DATEFORMAT DMY
USE QLBH
INSERT INTO KHACHHANG(MAKH,HOTEN,DCHI,SODT,NGSINH,DOANHSO,NGDK)
VALUES ('KH16','ABC','DCHI100','09123842','01/03/1979',70000,'14/11/2020')
INSERT INTO HOADON(SOHD,NGHD,MAKH,MANV,TRIGIA) VALUES (1066,'14/11/2006','KH16','NV03',250000)

UPDATE KHACHHANG
SET NGDK='14/11/2022'
WHERE MAKH='KH01'
UPDATE HOADON
SET NGHD='14/11/2021'
WHERE MAKH='KH01'
-- CURSOR
USE QLBH
DROP TRIGGER HOADON_TRIGGER
CREATE TRIGGER HOADON_TRIGGER ON HOADON
FOR UPDATE,INSERT
AS
BEGIN
    DECLARE @NGAYHD smalldatetime, @MAKH CHAR(4), @NGAYDK SMALLDATETIME
    SELECT @NGAYHD=NGHD, @MAKH=MAKH
    FROM INSERTED
    DECLARE CUR_KHACHHANG CURSOR
    FOR 
        SELECT NGDK
        FROM KHACHHANG
        WHERE MAKH=@MAKH
    OPEN CUR_HOADON
    FETCH NEXT FROM CUR_HOADON
    INTO @NGAYDK
    WHILE (@@FETCH_STATUS=0)
    BEGIN
        IF (@NGAYHD<@NGAYDK)
            SELECT NGDK
            FROM KHACHHANG
            WHERE MAKH=@MAKH
            BEGIN
                PRINT 'LOI: NGAY HOA DON KHONG HOP LE!'
                ROLLBACK TRANSACTION
             END
        ELSE
            BEGIN
                PRINT 'THEM MOT HOA DON THANH CONG!'
            END
        FETCH NEXT FROM CUR_HOADON
        INTO @NGAYDK
    END
    CLOSE CUR_KHACHHANG
    DEALLOCATE CUR_KHACHHANG 
END

DROP TRIGGER HOADON_TRIGGER
CREATE TRIGGER HOADON_TRIGGER ON KHACHHANG
FOR UPDATE
AS
BEGIN
    DECLARE @NGAYHD smalldatetime, @MAKH CHAR(4), @NGAYDK SMALLDATETIME
    SELECT @NGAYDK=NGDK, @MAKH=MAKH
    FROM INSERTED
    DECLARE CUR_KHACHHANG CURSOR
    FOR 
        SELECT NGHD
        FROM HOADON
        WHERE MAKH=@MAKH
    OPEN CUR_KHACHHANG
    FETCH NEXT FROM CUR_KHACHHANG
    INTO @NGAYHD
    WHILE (@@FETCH_STATUS=0)
    BEGIN
        SELECT @NGAYHD=NGHD
        FROM HOADON
        WHERE MAKH=@MAKH
        IF (@NGAYHD<@NGAYDK)
            BEGIN
                PRINT 'LOI: NGHD PHAI LON HON NGDK!'
                ROLLBACK TRANSACTION
             END
        ELSE
            BEGIN
                PRINT 'THEM MOT HOA DON THANH CONG!'
            END
        FETCH NEXT FROM CUR_KHACHHANG
        INTO @NGAYHD
    END
    CLOSE CUR_KHACHHANG
    DEALLOCATE CUR_KHACHHANG 
END

 



